name: CI
on:
  pull_request:
    branches: [ develop, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  e2e:
    name: End-to-End Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: HOST=https://staging.vbrdnk.dev/ yarn playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      # Speed up subsequent runs with caching
      - name: Cache node modules
        uses: actions/cache@v2

      # Install required deps for action
      - name: Install Dependencies
        run: yarn

      # Finally, run our tests
      - name: Run unit tests
        run: yarn test:unit